server:
  port: 8082

spring:
  application:
    name: clarity-backend

  datasource:
    #    url: jdbc:sqlserver://localhost;databaseName=clarity_db;encrypt=true;trustServerCertificate=true
    url: jdbc:postgresql://localhost:5432/clarity_db
    username: postgres
    password: raushan7
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration

  security:
    user:
      name: disabled
      password: disabled

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    com.clarity: DEBUG

jwt:
  secret: d8DGrY0ofn/l/QFTtKC7go6FiqdYUiVJ0ogzPBAU+3w=
  expiration: 86400000   # 1 day in ms

vertex:
  project-id: chatbot-487420
  location: us-central1
  #  model: gemini-2.0-flash-001
  model: gemini-2.5-flash-lite
#  credentials-path: C:/secure/chatbot-487420-c888f55f4abb.json


#GOOGLE_APPLICATION_CREDENTIALS: C:\secure\chatbot-487420-c888f55f4abb.json